layout: sidebar
style: light

collections:
  pages:
    output: true
    permalink: /:path

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /blog/:title/

important_pages:
  - About me
  - Programming
  - Research
  - Projects
  - Teaching
  - Random

repositories:
  - knowledge-learning/ehealthkd-2019
  - jsonapi
  - matcom/compilers
  - to

