layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# topics:
#   - name: Machine Learning
#     web_url: https://github.com/topics/machine-learning
#     image_url: https://en.wikipedia.org/wiki/Machine_learning#/media/File:Kernel_Machine.svg

#   - name: Artificial Intelligence
#     web_url: https://github.com/topics/artificial-intelligence
#     image_url: https://cdn.vox-cdn.com/thumbor/DUP2JhIEkY0yvu0RLcy34ipj6Z0=/0x0:1200x808/1200x800/filters:focal(475x111:667x303)/cdn.vox-cdn.com/uploads/chorus_image/image/55061015/wall_ecover.0.jpg

#   - name: Python
#     web_url: https://github.com/topics/python
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
  
