layout: sidebar
style: light

collections:
  pages:
    output: true
    permalink: /:path

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

important_pages:
  - About me
  - Programming
  - Research

repositories:
  - ehealthkd-2019
  - jsonapi
  - compilers
